-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.productos DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.pedidos DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.pedidos DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.clientes;

CREATE TABLE IF NOT EXISTS public.clientes
(
    cliente_id serial NOT NULL,
    nombre character varying(100),
    correo character varying(100),
    PRIMARY KEY (cliente_id)
);

DROP TABLE IF EXISTS public.productos;

CREATE TABLE IF NOT EXISTS public.productos
(
    id_producto serial NOT NULL,
    nombre_producto character varying(100),
    stock character varying(100) NOT NULL,
    precio character varying(100) NOT NULL,
    categoria integer,
    PRIMARY KEY (id_producto)
);

DROP TABLE IF EXISTS public.categorias;

CREATE TABLE IF NOT EXISTS public.categorias
(
    id_categoria serial NOT NULL,
    nombre_categoria character varying(100),
    PRIMARY KEY (id_categoria)
);

DROP TABLE IF EXISTS public.pedidos;

CREATE TABLE IF NOT EXISTS public.pedidos
(
    id_cliente integer NOT NULL,
    fecha character varying(100)[] NOT NULL,
    producto integer NOT NULL
);

ALTER TABLE IF EXISTS public.productos
    ADD FOREIGN KEY (categoria)
    REFERENCES public.categorias (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pedidos
    ADD FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pedidos
    ADD FOREIGN KEY (producto)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

