-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clientes
(
    cliente_id serial NOT NULL,
    nombre character varying(100),
    correo character varying(100),
    PRIMARY KEY (cliente_id)
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id_producto serial NOT NULL,
    nombre_producto character varying(100),
    stock character varying(100) NOT NULL,
    precio character varying(100) NOT NULL,
    categoria integer,
    PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    id_categoria character varying(100),
    nombre_categoria character varying(100)
);

CREATE TABLE IF NOT EXISTS public.pedidos
(
    id_cliente character varying(100)[] NOT NULL,
    fecha character varying(100)[] NOT NULL,
    producto character varying(100)[] NOT NULL
);

ALTER TABLE IF EXISTS public.clientes
    ADD FOREIGN KEY (cliente_id)
    REFERENCES public.pedidos (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.productos
    ADD FOREIGN KEY (categoria)
    REFERENCES public.categorias (nombre_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pedidos
    ADD FOREIGN KEY (producto)
    REFERENCES public.productos (nombre_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;