-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categorias
(
    id_categoria serial NOT NULL,
    nombre_categoria character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    cliente_id serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    correo character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT clientes_pkey PRIMARY KEY (cliente_id)
);

CREATE TABLE IF NOT EXISTS public.pedidos
(
    id_cliente integer NOT NULL,
    fecha character varying(100)[] COLLATE pg_catalog."default" NOT NULL,
    producto integer NOT NULL,
    cantidad integer
);

CREATE TABLE IF NOT EXISTS public.productos
(
    id_producto serial NOT NULL,
    nombre_producto character varying(100) COLLATE pg_catalog."default",
    stock integer NOT NULL,
    precio integer NOT NULL,
    categoria integer,
    CONSTRAINT productos_pkey PRIMARY KEY (id_producto)
);

ALTER TABLE IF EXISTS public.pedidos
    ADD CONSTRAINT pedidos_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (cliente_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pedidos
    ADD CONSTRAINT pedidos_producto_fkey FOREIGN KEY (producto)
    REFERENCES public.productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.productos
    ADD CONSTRAINT productos_categoria_fkey FOREIGN KEY (categoria)
    REFERENCES public.categorias (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

insert into clientes (nombre, correo) values
('Juan Pérez', 'juan@gmail.com'),
('Ana Gómez', 'ana@gmail.com'),
('Carlos Muñoz', 'carlos@gmail.com'),
('María López', 'maria@gmail.com'),
('Pedro Rivas', 'pedro@gmail.com'),
('Lucía Fuentes', 'lucia@gmail.com'),
('Diego Morales', 'diego@gmail.com'),
('Sofía Vega', 'sofia@gmail.com'),
('Javier Castro', 'javier@gmail.com'),
('Valentina Ruiz', 'valentina@gmail.com');


insert into productos (nombre_producto, precio, stock, categoria) values
('Laptop Lenovo', 650000, 10, 5),
('Laptop HP', 720000, 8, 5),
('Mouse Logitech', 15000, 50, 3),
('Teclado Mecánico', 35000, 25, 3),
('Monitor Samsung 24"', 120000, 12, 4),
('SSD 480GB', 45000, 30, 2),
('Memoria RAM 16GB', 60000, 18, 2),
('Pendrive 32GB', 9000, 100, 2),
('Audífonos Sony', 25000, 20, 3),
('Webcam Full HD', 30000, 15, 3),
('Parlantes Bluetooth', 28000, 22, 3),
('Silla Gamer', 150000, 5, 7),
('Router TP-Link', 28000, 19, 3),
('Impresora HP', 90000, 7, 7),
('Tablet Samsung', 140000, 10, 7),
('Mouse Pad XL', 8000, 40, 7),
('Cargador Universal', 12000, 35, 1),
('Hub USB 4 Puertos', 10000, 28, 7),
('MicroSD 128GB', 22000, 32, 2),
('Smartwatch Xiaomi', 65000, 14, 7);


insert into categorias (nombre_categoria) values
('Cargadores'),
('Componentes'),
('Perifericos'),
('Monitores'),
('Laptops'),
('Extraibles'),
('Accesorios');

add constraint ck_stock check (cast (stock as integer) > 0);
alter table pedidos add column cantidad varchar(100); 
alter table pedidos alter column cantidad type integer using cantidad::integer;
alter table pedidos alter column producto type integer using producto::integer;
alter table productos alter column precio type integer using precio::integer;
alter table productos alter column stock type integer using stock::integer;

insert into pedidos (id_cliente, fecha, producto, cantidad) values 
(7, '{17-10-2025}', 27, 3),
(3, '{24-10-2025}', 29, 4),
(5, '{10-10-2025}', 31, 6),
(6, '{31-11-2025}', 31, 2),
(3, '{01-11-2025}', 31, 7),
(1, '{01-11-2025}', 30, 5),
(4, '{03-11-2025}', 28, 6),
(7, '{07-11-2025}', 27, 1),
(9, '{10-11-2025}', 29, 10),
(7, '{15-11-2025}', 45, 3),
(5, '{10-11-2025}', 40, 5),
(10, '{23-11-2025}', 36, 8),
(3, '{22-11-2025}', 30, 1);
